export const productData = [
    {
      id: 1,
      imageUrl: "/Suggestion/img J.png",
      name: "Gradient Graphic T-shirt",
      price: 145,
      rating: 3.5,
    },
    {
      id: 2,
      imageUrl: "/Suggestion/img K.png",
      name: "Polo with Tipping Details",
      price: 180,
      rating: 4.5,
    },
    {
      id: 3,
      discount: 30,
      imageUrl: "/Suggestion/img L.png",
      name: "Black Striped T-shirt",
      price: 120,
      originalPrice: 150,
      rating: 5.0,
    },
    {
      id: 4,
      discount: 20,
      imageUrl: "/Newarrival/img B.png",
      name: "SKINNY FIT JEANS",
      price: 240,
      originalPrice: 260,
      rating: 3.5,
    },
    {
      id: 5,
      imageUrl: "/Newarrival/img C.png",
      name: "CHECKERED SHIRT",
      price: 180,
      rating: 4.5,
    },
    {
      id: 6,
      discount: 30,
      imageUrl: "/Newarrival/img D.png",
      name: "SLEEVE STRIPED T-SHIRT",
      price: 130,
      originalPrice: 160,
      rating: 4.5,
    },
    {
      id: 7,
      discount: 20,
      imageUrl: "/Topselling/img M.png",
      name: "VERTICAL STRIPED SHIRT",
      price: 212,
      originalPrice: 232,
      rating: 5.0,
    },
    {
      id: 8,
      imageUrl: "/Topselling/img N.png",
      name: "COURAGE GRAPHIC T-SHIRT",
      price: 145,
      rating: 4.0,
    },
    {
      id: 9,
      imageUrl: "/Topselling/img O.png",
      name: "LOOSE FIT BERMUDA SHORTS",
      price: 80,
      rating: 3.0,
    },
  
  ];